### ISSUE TITLE
extrapolateInSpaceToFace

### ISSUE THREAD

**Issue by zhangruoyao68** [pmocz/finitevolume-python#3]
I am a bit confused about the function `extrapolateInSpaceToFace(...)`, specifically
```
f_XL = f - f_dx * dx/2
f_XL = np.roll(f_XL,R,axis=0)
f_XR = f + f_dx * dx/2
  
f_YL = f - f_dy * dx/2
f_YL = np.roll(f_YL,R,axis=1)
f_YR = f + f_dy * dx/2
``` 
Could you explain why f_XL and f_YL are rolled, such that f_XL (i,j) in fact holds the value of f_XL(i+1,j)? I thought these are matrices storing 4 face values of the cell (i,j). Thank you!

**Comment by pmocz** [comment]
Great question! At this point I'm gearing up to compare the extrapolated states that border faces. So, for example, cell i extrapolated to the right would touch the same face as cell i+1 extrapolated to the left. Hence the np.roll(). The notation may be a little confusing. The indexing of f_XL is i+1 centric, not i centric
